# supabase/config.toml

# The project_id should be your project's reference ID from the Supabase dashboard URL.
# It looks like: abcdefghijklmnopqrst
# The organization_id is not needed here.
project_id = "your-project-ref-id"

[api]
port = 54321
schemas = ["public", "storage"]
extra_schemas = ["auth"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

# Defines the Edge Functions in your project
[functions]
create-checkout-session = {}
stripe-webhook = {}
