# This is a GitHub Actions workflow file.
# It automates the process of deploying your Supabase Edge Functions.

name: Deploy Supabase Functions

on:
  # This workflow runs automatically whenever you push changes to the main branch.
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**' # It only runs if you change files inside the functions directory.
  
  # This allows you to run the workflow manually from the GitHub Actions tab if you need to.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Supabase Edge Functions
        run: |
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          # This is the correct secret that the deployment command needs.
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
